/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        'neutral': '#353638',
        'neutral-strong': '#222325',
        'neutral-medium': '#5C5D5F',
        'neutral-subtle': '#B5B6B8',
        'neutral-inverse': '#F2F3F5',
        'primary': '#1AA1E1',
        'primary-strong' : '#0E95D5',
        'primary-medium' : '#30B7F7',
        'primary-subtle' : '#4FD6FB',
        'primary-inverse' : '#D3FFFF',
        'accent' : '#CE5043',
        'accent-strong' : '#B23427',
        'accent-medium' : '#F6786B',
        'accent-subtle' : '#FFA396',
        'accent-inverse' : '#FFC9BC',
        'success' : '#B3C833',
        'success-strong' : '#859A05',
        'success-medium' : '#C6DB46',
        'success-subtle' : '#E6FB66',
        'success-inverse' : '#FFFFB0',
        'danger' : '#CE5043',
        'danger-strong' : '#B23427',
        'danger-medium' : '#F6786B',
        'danger-subtle' : '#FFA396',
        'danger-inverse' : '#FFC9BC',
        'warning' : '#EDB954',
        'warning-strong' : '#D6A03E',
        'warning-medium' : '#FFD977',
        'warning-subtle' : '#FFF08E',
        'warning-inverse' : '#FFFFCA',
      }
    },
  },
  plugins: [],
}
